# Simplified Build workflow using uv and its setup action
# This workflow uses the official `astral-sh/setup-uv` action which
# installs uv, configures Python, and optionally handles uv's cache.

name: Build

on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    name: Build on ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: 'Windows'
            os: windows-latest
            python-version: '3.8'
            artifact-name: RootPainterInstaller.exe
          - name: 'Ubuntu'
            os: ubuntu-latest
            python-version: '3.10'
            artifact-name: RootPainter.deb
          - name: 'macOS'
            os: macos-latest
            python-version: '3.9.5'
            artifact-name: RootPainter.pkg

    steps:
      - uses: actions/checkout@v4

      - name: Set up uv and Python
        uses: astral-sh/setup-uv@v6

      - name: Build software (PyInstaller)
        working-directory: painter
        run: |
          # Run the PyInstaller build inside the uv-managed python
          uv run --project painter run --python ${{ matrix.config.python-version }} python scripts/run_pyinstaller.py

      - name: Make installer (macOS)
        if: runner.os == 'macOS'
        working-directory: painter
        run: |
          uv run --project painter pkgbuild --component dist/RootPainter.app --install-location /Applications dist/RootPainter.pkg

      - name: Make installer (Linux)
        if: runner.os == 'Linux'
        working-directory: painter
        run: |
          uv --project painter run scripts/make_deb_file

      - name: Make installer (Windows)
        if: runner.os == 'Windows'
        working-directory: painter
        run: |
          makensis.exe scripts/assets/Installer.nsi

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: Package-${{ matrix.config.name }}
          path: ${{github.workspace}}/painter/dist/${{ matrix.config.artifact-name }}
          if-no-files-found: error

      - name: Publish packages to PyPI with poe
        if: startsWith(github.ref, 'refs/tags/')
        shell: bash
        run: |
          uv run poe release
        env:
          POE_PUBLISH_INDEX: pypi
