---
name: Test
on:
  pull_request:
  push:
    branches-ignore: [main]
jobs:
  test:
    name: UI tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup UV and Python (cached)
        uses: astral-sh/setup-uv-and-handle-its-cache@v1
        with:
          python-version: '3.10'
          cache: true
      - name: Install system packages required by Qt
        run: |
          sudo apt-get update
          sudo apt-get install -y libegl1-mesa libgl1-mesa-glx libxkbcommon0
      - name: Sync/Install Python dependencies
        run: uv sync --dev
      - name: Run painter UI tests (headless)
        env:
          QT_QPA_PLATFORM: offscreen
          PYTHONUNBUFFERED: 1
        run: .venv/bin/pytest -q tests/painter -o qt_api=pyqt6
